steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'src/${_NAME}'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/gfm-${_NAME}:latest', 
    '-t', 'gcr.io/$PROJECT_ID/gfm-${_NAME}:$COMMIT_SHA', 
    '.'
    ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/gfm-${_NAME}:$COMMIT_SHA'
    ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/gfm-${_NAME}:latest'
    ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run',
    'deploy',
    'gfm-${_NAME}',
    '--image=gcr.io/$PROJECT_ID/gfm-${_NAME}:latest',
    '--allow-unauthenticated',
    '--port=80',
    ]