steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'src/basket'
  args: [
    'build',
    '-t', 'gcr.io/${_NAME}/gfm-basket:latest', 
    '-t', 'gcr.io/${_NAME}/gfm-basket:$COMMIT_SHA', 
    '.'
    ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/gfm-basket'
    ]